version: '3'
services:
  nginx:
    image: 'nginx:latest'
    command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './www:/srv/http/www'
    network_mode: 'host'
    restart: 'always'
    logging:
      options:
        max-size: '10m'
        max-file: '50'
  auth_server:
    image: 'auth_server'
    network_mode: 'host'
    restart: 'always'
    environment:
      PORT: 8080
      TOKEN: 'jigentec'
    logging:
      options:
        max-size: '10m'
        max-file: '50'
