version: '3'
services:
  nginx:
    image: 'nginx:latest'
    command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './www:/srv/http/www'
      - './certbot/conf:/etc/letsencrypt'
      - './certbot/www:/var/www/certbot'
      - './certbot/conf/live/image-detection.jigentec.com/fullchain.pem:/etc/ssl/fullchain.pem:ro'
      - './certbot/conf/live/image-detection.jigentec.com/privkey.pem:/etc/ssl/privkey.pem:ro'
    network_mode: 'host'
    restart: 'always'
    logging:
      options:
        max-size: '10m'
        max-file: '50'
  auth_server:
    image: 'auth_server'
    network_mode: 'host'
    restart: 'always'
    environment:
      PORT: 8080
      TOKEN: 'jigentec'
    logging:
      options:
        max-size: '10m'
        max-file: '50'
  certbot:
    image: 'certbot/certbot'
    volumes:
      - './certbot/conf:/etc/letsencrypt/:rw'
      - './certbot/www:/var/www/certbot/:rw'
      - './var:/var/log/:rw'
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    logging:
      options:
        max-size: '10m'
        max-file: '10'
